name: Unittests & Auto-publish

# Run on pushes to `main`, and on every pull request.
# Also allow to trigger the workflow manually (e.g. when deps changes).
on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

# Deny all permissions by default; each job opts in to what it needs.
permissions: {}

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v6

    # Install deps
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        # Uncomment to cache of pip dependencies (if tests too slow)
        # cache: pip
        # cache-dependency-path: '**/pyproject.toml'

    - run: pip --version
    - run: pip install -e .[dev]
    - run: pip freeze

    # Run tests (in parallel)
    - name: Run core tests
      run: pytest -vv -n auto

  # Auto-publish when version is increased
  publish-job:
    # Only try to publish if:
    # * Repo is self (prevents running from forks)
    # * Branch is `main`
    if: |
      github.repository == 'google-deepmind/disentangled_rnns'
      && github.ref == 'refs/heads/main'
    needs: pytest-job  # Only publish after tests are successful
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30

    steps:
    # Publish the package (if local `__version__` > pip version)
    #
    # Select a specific version of the pypi-auto-publish tool using a SHA hash, which is more secure
    # than a version number. This is because the version number is a mutable pointer that could
    # be redirected by a malicious actor if pypi-auto-publish were compromised. This is important
    # for pypi-auto-publish because it is used to publish our code to the public PyPI repository.
    # If we decide to update to a new version of pypi-auto-publish, we should update both the SHA
    # hash and the version number. We shouldn't need to do this often.
    - uses: etils-actions/pypi-auto-publish@d0603b1e896ce8b754fd7df30731623c93546e89  # v1.5.6
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        parse-changelog: true
